on:
  push:
    tags:
      - '*'

name: Release to terraform public registry
jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
    - uses: ncipollo/release-action@v1.13.0
      with:
        generateReleaseNotes: true
        name: "v${{ github.ref_name }}"
        token: ${{ secrets.GITHUB_TOKEN }}